#Exercícios com NumPy

##### Importar NumPy como np

In [9]:
import numpy as np

####Criar uma array com 10 zeros

In [10]:
array_1 = np.zeros(10)
array_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

####Criar uma array com 10 uns

In [12]:
array_2 = np.ones(10)
array_2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

####Criar um array com 10 cincos

In [13]:
array_3 = np.ones(10) * 5
array_3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

####Criar um array com os inteiros de 10 até 50

In [14]:
array_4 = np.arange(10,51)
array_4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

####Criar uma matriz 3x3 com valores de 0 a 8

In [68]:
matriz_1 = np.arange(9).reshape(3,3)
matriz_1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

####Criar uma matriz identidade 3x3

In [69]:
matriz_2 = np.arange(9).reshape(3,3)
matriz_2[:] = 3
matriz_2

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

####Utilize o NumPy para gerar um número entre 0 e 1

In [32]:
random = np.random.rand(1)
random

array([0.86991417])

####Utilize o NumPy para gerar um array de 25 números aleatórios de uma amostra retirada de uma distribuição normal padrão

In [34]:
array_5 = np.random.rand(25)
array_5

array([0.27987036, 0.83063672, 0.48421989, 0.93522144, 0.46813885,
       0.12684287, 0.96194215, 0.90172275, 0.06149415, 0.66072058,
       0.35973577, 0.35896902, 0.42185049, 0.31700238, 0.1307661 ,
       0.06480517, 0.13651823, 0.89928724, 0.11995413, 0.82651437,
       0.54879936, 0.32065339, 0.48131933, 0.96732078, 0.85844657])

####Crie a seguinte matriz

In [37]:
#Digite seu código aqui
array_6 = np.arange(1,101).reshape(10,10) / 100
array_6

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

####Crie um array de 20 pontos linearmente espaçados entre 0 e 1

In [39]:
#Digite seu código aqui
array_7 = np.linspace(0,1,20)
array_7

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#NumPy Indexação e Seleção
Agora serão dadas algumas matrizes e você deve replicar os resultados apresentados na sequência

In [41]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
#Digite seu código aqui
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [53]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [56]:
#Digite seu código aqui
mat[3,4]

20

In [54]:
mat[3,4]

20

In [60]:
#Digite seu código aqui
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [61]:
#Digite seu código aqui
mat[4,:]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [62]:
#Digite seu código aqui
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#Agora faça o seguinte
####Obtenha a soma de todos os valores em mat

In [63]:
mat.sum()

325

####Obtenha o desvio padrão dos valores em mat

In [64]:
mat.std()

7.211102550927978

####Obtenha a soma de todas as colunas em mat

In [65]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])